import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins, Roboto } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { QueryClientProvider } from "@tanstack/react-query";
import queryClient from "@/lib/query-client";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";
import { CalendarProvider } from "@/context/date-provider-context";

// Fontes Importadas do Google
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  weight: ['100', '400', '500', '700'],
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ['100', '400', '500', '700'],
});

export const metadata: Metadata = {
  title: "Atlas",
  icons: {
      icon: "logo.svg"
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, minimal-ui" />
        </head>
      <body
        className={`${poppins.variable} ${geistSans.variable} ${geistMono.variable} ${roboto.className} antialiased dark:bg-[#0a0a0a] s`}
      >
        <QueryClientProvider client={queryClient}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
            storageKey="theme"
          >
            <ClerkProvider>
              <CalendarProvider>
                <Toaster position="top-center" richColors duration={1000} />
                {children}
              </CalendarProvider>
            </ClerkProvider>
          </ThemeProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
